name: Install ArgoCD
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::160071257600:role/dev-github-actions-role
          aws-region: us-east-1

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name dev-my-eks-cluster --region us-east-1

      - name: Test kubectl access
        run: |
          kubectl get nodes

      - name: Install ArgoCD via Helm
        run: |
          # 1. Create Namespace (if not exists)
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          
          # 2. Add Helm Repo
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          
          # 3. Install ArgoCD
          # We set service.type=LoadBalancer so you can access the UI easily
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --version 5.46.7 \
            --set server.service.type=LoadBalancer \
            --set server.insecure=true

      